version: '2'
services:
  oracle:
    build:
      context: .
    env_file:
      - .env
    environment:
      MONGO_HOST: mongodb://mongo:27017
      FLASK_DEBUG: 1
    volumes:
      - .:/oracle
  mongo:
    image: mongo:latest
    volumes:
      - mongo:/data/db
    ports:
      - "27017:27017"
volumes:
  mongo:
