version: '2'
services:
  oracle:
    build:
      context: .
    env_file:
      - .env
    environment:
      MONGO_HOST: mongodb://mongo:27017
      FLASK_DEBUG: 1
    # volumes:
      # - .:/usr/src/app
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
